### PR TITLE
extended and more flexible network settings & defaults

### PR DESCRIPTION
**Pull request by cfoellmann**
SEE: #7 

Lets start with these minor changes

### CODE REVIEW

**Comment by nosilver4u** [comment]
Looks like the PHPCS checks are failing currently: https://travis-ci.com/nosilver4u/imsanity/builds/102423130
I'll take a closer look at the actual code next week, been slogging through some tricky plugin conflicts on EWWW IO this week (yuck).

**Comment by cfoellmann** [comment]
I will try to correct the Code style

**Comment by nosilver4u** [comment]
Also, the Domain Path isn't actually necessary for Imsanity since it's hosted on wp.org: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#domain-path

**Comment by cfoellmann** [comment]
Sorry for my long absence.
Can you have a quick look if anything of this is still valid? I suspect most of it is already done by you

**Comment by nosilver4u** [comment]
I made some fixes in the multi-site settings for the last release, but I haven't had a chance to go beyond that yet.

**Comment by nosilver4u** [comment]
Since the branch had conflicts at this point, I've merged all the tweaks and fixes manually.
I also added filters for the permissions on the settings page(s).

**Pull request closed without merging**
